### ISSUE TITLE
Erro de Kernel

### ISSUE THREAD

**Issue by hdneves** [AlertaDengue/PySUS#169]
Alguém saberia me explicar o que seria esse erro de Kernel?

`
import os
from pysus.utilities.readdbc import read_dbc

arquivos = '/mnt/d/VSCODE_DEMANT/Automatização SOW/Dados'

arq = [item for item in os.listdir(arquivos) if item.endswith('PABA2308.dbc')]
arq

for arquivo in arq:
    print(arquivo)
    caminho_completo = os.path.join(arquivos, arquivo)
    df = read_dbc(caminho_completo, encoding='iso-8859-1')

`

output: **O Kernel falhou ao executar o código na célula atual ou em uma célula anterior. Examine o código nas células para identificar uma possível causa da falha. Clique [aqui](https://aka.ms/vscodeJupyterKernelCrash) para obter mais informações. Consulte o [log](command:jupyter.viewOutput) do Jupyter para obter mais detalhes.**

**Comment by hdneves** [comment]
14:36:11.186 [info] Start refreshing Kernel Picker (1699292171186)
14:36:11.191 [info] Using Pylance
14:36:12.776 [info] End refreshing Kernel Picker (1699292171186)
14:36:13.227 [warn] No interpreter for Pylance for Notebook URI "/mnt/c/Users/hdsou/OneDrive/Documentos/vscode - ubuntu/teste/datasus.ipynb"
14:36:16.179 [info] Start refreshing Kernel Picker (1699292176179)
14:36:17.355 [info] End refreshing Kernel Picker (1699292176179)
14:36:18.338 [info] Handle Execution of Cells 4 for /mnt/c/Users/hdsou/OneDrive/Documentos/vscode - ubuntu/teste/datasus.ipynb
14:36:18.342 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher  (Python Path: /bin/python3, Unknown, 3.10.12) for '/mnt/c/Users/hdsou/OneDrive/Documentos/vscode - ubuntu/teste/datasus.ipynb' (disableUI=false)
14:36:18.395 [warn] Failed to get activated env vars for /bin/python3 in 71ms
14:36:18.406 [info] Process Execution: /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
14:36:18.415 [error] Unable to determine site packages path for python /bin/python3 (Unknown)
14:36:18.421 [info] Process Execution: /bin/python3 -m pip list
14:36:18.451 [warn] Failed to get activated env vars for /bin/python3 in 89ms
14:36:18.452 [error] Unable to determine site packages path for python /bin/python3 (Unknown)
14:36:18.460 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:36:18.469 [info] Process Execution: /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"46d3f861-68cc-4808-9738-5d2af1a234a2" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-8140sjffXzXvXSp.json
    > cwd: /mnt/c/Users/hdsou/OneDrive/Documentos/vscode - ubuntu/teste
14:36:18.693 [info] ipykernel version & path 6.26.0, ~/.local/lib/python3.10/site-packages/ipykernel/__init__.py for /bin/python3
14:36:19.140 [info] Process Execution: /bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.10.1003070148-linux-x64/pythonFiles/printJupyterDataDir.py
14:36:19.150 [info] Kernel acknowledged execution of cell 4 @ 1699292179149
14:36:19.756 [info] End cell 4 execution @ 1699292179756, started @ 1699292179149, elapsed time = 0.607s
14:37:51.805 [info] Handle Execution of Cells 4 for /mnt/c/Users/hdsou/OneDrive/Documentos/vscode - ubuntu/teste/datasus.ipynb
14:37:51.813 [info] Kernel acknowledged execution of cell 4 @ 1699292271813
14:37:51.818 [info] End cell 4 execution @ 1699292271818, started @ 1699292271813, elapsed time = 0.005s
14:37:51.818 [warn] Cancel all remaining cells due to cancellation or failure in execution
14:37:53.966 [info] Handle Execution of Cells 4 for /mnt/c/Users/hdsou/OneDrive/Documentos/vscode - ubuntu/teste/datasus.ipynb
14:37:53.972 [info] Kernel acknowledged execution of cell 4 @ 1699292273972
14:47:21.903 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 
14:47:21.918 [info] Dispose Kernel process 1296.
14:47:22.227 [info] End cell 4 execution @ undefined, started @ 1699292273972, elapsed time = -1699292273.972s
18:39:01.301 [info] Handle Execution of Cells 4 for /mnt/c/Users/hdsou/OneDrive/Documentos/vscode - ubuntu/teste/datasus.ipynb
18:39:02.552 [info] Restart requested /mnt/c/Users/hdsou/OneDrive/Documentos/vscode - ubuntu/teste/datasus.ipynb
18:39:02.559 [warn] Cancel all remaining cells due to cancellation or failure in execution
18:39:02.833 [warn] Failed to get activated env vars for /bin/python3 in 263ms
18:39:02.835 [error] Unable to determine site packages path for python /bin/python3 (Unknown)
18:39:02.851 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
18:39:02.864 [info] Process Execution: /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"466bdd9b-9039-48d1-ba38-8b168bfd90cb" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-814awDs6Kgo8D3t.json
    > cwd: /mnt/c/Users/hdsou/AppData/Local/Programs/Microsoft VS Code
18:39:03.383 [warn] Stderr output when getting ipykernel version & path Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 945, in _find_spec
    File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
    File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
    File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
    File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
    OSError: [Errno 5] Input/output error: '/mnt/c/Users/hdsou/AppData/Local/Programs/Microsoft VS Code' for /bin/python3
18:39:05.135 [info] Restarted 1b292d76-b03f-4cdb-abce-06c2a98517eb
18:39:05.178 [info] Kernel acknowledged execution of cell 4 @ 1699306745178
18:56:23.279 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 
18:56:23.291 [info] Dispose Kernel process 52823.
18:56:23.621 [info] End cell 4 execution @ undefined, started @ 1699306745178, elapsed time = -1699306745.178s
