### ISSUE TITLE
Problem reading the data: File is not available

### ISSUE THREAD

**Issue by ivazora** [AlertaDengue/PySUS#30]
Tried to follow the example from here:  https://pysus.readthedocs.io/en/latest/SINAN.html
It looks like files are no longer available:

"""
Attempt to follow this example:
    https://pysus.readthedocs.io/en/latest/SINAN.html
"""
from pysus.online_data import SINAN
import pandas as pd

SINAN.list_diseases()
"""Out[2]: 
['Animais Peçonhentos',
 'Botulismo',
 'Chagas',
 'Colera',
 'Coqueluche',
 'Dengue',
 'Difteria',
 'Esquistossomose',
 'Febre Amarela',
 'Febre Maculosa',
 'Febre Tifoide',
 'Hanseniase',
 'Hantavirose',
 'Hepatites Virais',
 'Intoxicação Exógena',
 'Leishmaniose Visceral',
 'Leptospirose',
 'Leishmaniose Tegumentar',
 'Malaria',
 'Meningite',
 'Peste',
 'Poliomielite',
 'Raiva Humana',
 'Tétano Acidental',
 'Tétano Neonatal',
 'Tuberculose',
 'Violência Domestica']
"""

SINAN.get_available_years('RJ', 'chagas')

#ERROR example:
"""
SINAN.get_available_years('RJ', 'chagas')
Traceback (most recent call last):

  File "<ipython-input-3-8a6f7abc782a>", line 1, in <module>
    SINAN.get_available_years('RJ', 'chagas')

AttributeError: module 'pysus.online_data.SINAN' has no attribute 'get_available_years'
"""
df = SINAN.download('SP',2018,'Chagas')

#ERROR:
"""    
    df = SINAN.download('SP',2018,'Chagas')
Traceback (most recent call last):

  File "/home/yanchik/anaconda3/lib/python3.8/site-packages/pysus/online_data/SINAN.py", line 66, in download
    ftp.retrbinary('RETR {}'.format(fname), open(fname, 'wb').write)

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 348, in ntransfercmd
    resp = self.sendcmd(cmd)

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 275, in sendcmd
    return self.getresp()

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 248, in getresp
    raise error_perm(resp)

error_perm: 550 The system cannot find the file specified. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yanchik/anaconda3/lib/python3.8/site-packages/pysus/online_data/SINAN.py", line 69, in download
    ftp.retrbinary('RETR {}'.format(fname.upper()), open(fname, 'wb').write)

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 348, in ntransfercmd
    resp = self.sendcmd(cmd)

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 275, in sendcmd
    return self.getresp()

  File "/home/yanchik/anaconda3/lib/python3.8/ftplib.py", line 248, in getresp
    raise error_perm(resp)

error_perm: 550 The system cannot find the file specified. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-4-653a99830bd6>", line 1, in <module>
    df = SINAN.download('SP',2018,'Chagas')

  File "/home/yanchik/anaconda3/lib/python3.8/site-packages/pysus/online_data/SINAN.py", line 71, in download
    raise Exception("{}\nFile {} not available".format(e,fname))

Exception: 550 The system cannot find the file specified. 
File ANIMSP18.DBC not available
"""

**Comment by fccoelho** [comment]
This is what I get here:
```python
In [3]: SINAN.get_available_years('RJ','chagas')                                                          
Out[3]: 
['CHAGRJ07.dbc',
 'CHAGRJ08.dbc',
 'CHAGRJ09.dbc',
 'CHAGRJ10.dbc',
 'CHAGRJ11.dbc',
 'CHAGRJ12.dbc',
 'CHAGRJ13.dbc',
 'CHAGRJ14.dbc',
 'CHAGRJ15.dbc',
 'CHAGRJ16.dbc',
 'CHAGRJ17.dbc',
 'CHAGRJ18.dbc']
```


Did you install PySUS from PyPI? Which version are you running?
```bash
pip freeze |grep PySUS
```
Since these are relatively new features, I think the latest version of PySUS on PyPI still did not include them. I have made a new release (0.4.9) to make sure these latest features are included. Please update your installation:
```bash
pip install -U PySUS
```

**Comment by ivazora** [comment]
Works now - Thank you!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
