### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by reichaves** [AlertaDengue/PySUS#7]
Olá

Tudo bem?
Parabéns pela iniciativa!
Por favor, em uma máquina com Ubuntu e Python 3.6 eu tentei instalar, mas tive esses erros abaixo
Eu preciso instalar outras bibliotecas ou outra ação?

Obrigado
Reinaldo

Hello

Congratulations for the initiative!
Please, on a machine with Ubuntu and Python 3.6 I tried to install, but I had these errors below
Do I need to install other libraries or other action?

Thank you
Reinaldo

$ pip install PySUS
Collecting PySUS
  Using cached https://files.pythonhosted.org/packages/bf/7b/28dd138e51a3f8774b96b535fb872e08c1f5cf974f53286e11de0d90259c/PySUS-0.1.12.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: Arquivo ou diretório não encontrado
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 169, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 155, in call_command
        self.run_command(cmdname)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
        self.run_command('build_ext')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-s_38by4p/cffi-1.11.5/setup.py", line 240, in <module>
      File "/usr/lib/python3.6/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
        run_setup(setup_script, args)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 257, in run_setup
        raise
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 170, in save_modules
        saved_exc.resume()
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 145, in resume
        six.reraise(type, exc, self._tb)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
        yield saved
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
        yield
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
        _execfile(setup_script, ns)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-s_38by4p/cffi-1.11.5/setup.py", line 240, in <module>
      File "/usr/lib/python3.6/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ixt2heob/PySUS/setup.py", line 41, in <module>
        install_requires=['pandas', 'dbfread', 'cffi>=1.0.0', 'geocoder', 'requests']
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ixt2heob/PySUS/

**Comment by fccoelho** [comment]
Oi Reinaldo,

você precisa instalar a libffi antes de instalar o Pysus:

```bash
sudo apt install libffi-dev
```
esta é uma dependencia do da biblioteca cffi do python.
vou adicionar esta informação ao README do  projeto

**Comment by reichaves** [comment]
Muito obrigado
Mas os arquivos DBF do SINASC e SINAN ainda não estão disponíveis, certo?

Tentei também ler a API (https://info.dengue.mat.br/services/api) mas a conexão é recusada: URLError: <urlopen error [Errno 111] Connection refused>


url = 'http://localhost:8000/api/alertcity'
# 3306305 = Volta Redonda city geocode
search_filter = (
    'geocode=3306305&disease=dengue&format=json&' +
    'ew_start=1&ew_end=50&ey_start=2017&ey_end=2018'
)
search_url = '%s?%s' % (url, search_filter)

df = pd.read_json(search_url)

**Comment by fccoelho** [comment]
O PySUS não se propõe a disponibilizar os DBFs, apenas a ajudar a analisar os DBF do SUS que o usuário tenha.

sobre a API, você está com a `url` errada, tente essa:
`https://info.dengue.mat.br/api/alertcity/`
