### ISSUE TITLE
This error originates from a subprocess - pip install pySUS

### ISSUE THREAD

**Issue by otavioaugust1** [AlertaDengue/PySUS#97]
Hello,

I'm having a problem installing pySUS that has the following erro:

```
 PS C:\Users\otavi\GitHub\MEGA_SENA-GERADOR_NUMERO_AI> pip install PySUS
Collecting PySUS
  Using cached pysus-0.6.1-py3-none-any.whl (1.8 MB)
Collecting numpy==1.23.2
  Using cached numpy-1.23.2-cp310-cp310-win_amd64.whl (14.6 MB)
Collecting dbfread==2.0.7
  Using cached dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Collecting elasticsearch<9.0.0,>=8.3.3
  Using cached elasticsearch-8.4.2-py3-none-any.whl (384 kB)
Collecting pyarrow<10.0.0,>=9.0.0
  Using cached pyarrow-9.0.0-cp310-cp310-win_amd64.whl (19.5 MB)
Collecting cffi==1.15.1
  Using cached cffi-1.15.1-cp310-cp310-win_amd64.whl (179 kB)
Collecting pytz==2022.2.1
  Using cached pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
Requirement already satisfied: pandas==1.4.3 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from PySUS) (1.4.3)
Collecting pyreaddbc==1.0.0
  Using cached pyreaddbc-1.0.0.tar.gz (43 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting jupyterlab<4.0.0,>=3.4.5
  Using cached jupyterlab-3.4.8-py3-none-any.whl (8.8 MB)
Collecting geocoder<2.0.0,>=1.38.1
  Using cached geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: python-dateutil==2.8.2 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from PySUS) (2.8.2)
Collecting pycparser==2.21
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Requirement already satisfied: six==1.16.0 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from PySUS) (1.16.0)
Collecting wget<4.0,>=3.2
  Using cached wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Collecting tqdm==4.64.0
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting fastparquet<0.9.0,>=0.8.1
  Using cached fastparquet-0.8.3-cp310-cp310-win_amd64.whl (603 kB)
Requirement already satisfied: colorama in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from tqdm==4.64.0->PySUS) (0.4.5)
Collecting elastic-transport<9,>=8
  Using cached elastic_transport-8.4.0-py3-none-any.whl (59 kB)
Requirement already satisfied: packaging in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from fastparquet<0.9.0,>=0.8.1->PySUS) (21.3)
Collecting cramjam>=2.3.0
  Using cached cramjam-2.5.0-cp310-none-win_amd64.whl (993 kB)
Collecting fsspec
  Using cached fsspec-2022.8.2-py3-none-any.whl (140 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
  Preparing metadata (setup.py) ... done
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting ratelim
  Using cached ratelim-0.1.6-py2.py3-none-any.whl (4.0 kB)
Collecting tomli
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Requirement already satisfied: tornado>=6.1.0 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.0.0,>=3.4.5->PySUS) (6.2)
Requirement already satisfied: jupyter-core in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.0.0,>=3.4.5->PySUS) (4.11.1)
Collecting notebook<7
  Using cached notebook-6.4.12-py3-none-any.whl (9.9 MB)
Collecting jupyter-server~=1.16
  Using cached jupyter_server-1.19.1-py3-none-any.whl (346 kB)
Requirement already satisfied: ipython in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jupyterlab<4.0.0,>=3.4.5->PySUS) (8.5.0)
Collecting jinja2>=2.1
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jupyterlab-server~=2.10
  Using cached jupyterlab_server-2.15.2-py3-none-any.whl (54 kB)
Collecting nbclassic
  Using cached nbclassic-0.4.4-py3-none-any.whl (9.8 MB)
Collecting certifi
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Requirement already satisfied: urllib3<2,>=1.26.2 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from elastic-transport<9,>=8->elasticsearch<9.0.0,>=8.3.3->PySUS) (1.26.12)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp310-cp310-win_amd64.whl (17 kB)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server~=1.16->jupyterlab<4.0.0,>=3.4.5->PySUS) (7.3.5)
Requirement already satisfied: pyzmq>=17 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server~=1.16->jupyterlab<4.0.0,>=3.4.5->PySUS) (24.0.1)
Collecting nbformat>=5.2.0
  Using cached nbformat-5.6.1-py3-none-any.whl (77 kB)
Collecting terminado>=0.8.3
  Using cached terminado-0.16.0-py3-none-any.whl (16 kB)
Collecting argon2-cffi
  Using cached argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting anyio<4,>=3.1.0
  Using cached anyio-3.6.1-py3-none-any.whl (80 kB)
Collecting websocket-client
  Using cached websocket_client-1.4.1-py3-none-any.whl (55 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting prometheus-client
  Using cached prometheus_client-0.14.1-py3-none-any.whl (59 kB)
Requirement already satisfied: traitlets>=5.1 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jupyter-server~=1.16->jupyterlab<4.0.0,>=3.4.5->PySUS) (5.4.0)
Collecting nbconvert>=6.4.4
  Using cached nbconvert-7.1.0-py3-none-any.whl (272 kB)
Collecting pywinpty
  Using cached pywinpty-2.0.8-cp310-none-win_amd64.whl (1.4 MB)
Requirement already satisfied: pywin32>=1.0 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jupyter-core->jupyterlab<4.0.0,>=3.4.5->PySUS) (304)
Collecting json5
  Using cached json5-0.9.10-py2.py3-none-any.whl (19 kB)
Collecting jsonschema>=3.0.1
  Using cached jsonschema-4.16.0-py3-none-any.whl (83 kB)
Collecting babel
  Using cached Babel-2.10.3-py3-none-any.whl (9.5 MB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: ipykernel in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from notebook<7->jupyterlab<4.0.0,>=3.4.5->PySUS) (6.16.0)
Requirement already satisfied: nest-asyncio>=1.5 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from notebook<7->jupyterlab<4.0.0,>=3.4.5->PySUS) (1.5.5)
Requirement already satisfied: pygments>=2.4.0 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (2.13.0)
Requirement already satisfied: backcall in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.2.0)
Requirement already satisfied: jedi>=0.16 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.1.6)
Requirement already satisfied: decorator in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (5.1.1)
Requirement already satisfied: pickleshare in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.7.5)
Requirement already satisfied: prompt-toolkit<3.1.0,>3.0.1 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (3.0.31)
Requirement already satisfied: stack-data in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.5.1)
Collecting notebook-shim>=0.1.0
  Using cached notebook_shim-0.1.0-py3-none-any.whl (13 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from packaging->fastparquet<0.9.0,>=0.8.1->PySUS) (3.0.9)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting sniffio>=1.1
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.8.3)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.18.1-cp310-cp310-win_amd64.whl (61 kB)
Collecting attrs>=17.4.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: entrypoints in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from jupyter-client>=6.1.12->jupyter-server~=1.16->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.4)
Collecting mistune<3,>=2.0.3
  Using cached mistune-2.0.4-py2.py3-none-any.whl (24 kB)
Collecting pandocfilters>=1.4.1
  Using cached pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting bleach
  Using cached bleach-5.0.1-py3-none-any.whl (160 kB)
Collecting jupyterlab-pygments
  Using cached jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting tinycss2
  Using cached tinycss2-1.1.1-py3-none-any.whl (21 kB)
Collecting nbclient>=0.5.0
  Using cached nbclient-0.6.8-py3-none-any.whl (71 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting fastjsonschema
  Using cached fastjsonschema-2.16.2-py3-none-any.whl (22 kB)
Requirement already satisfied: wcwidth in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from prompt-toolkit<3.1.0,>3.0.1->ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.2.5)
Collecting argon2-cffi-bindings
  Using cached argon2_cffi_bindings-21.2.0-cp36-abi3-win_amd64.whl (30 kB)
Requirement already satisfied: debugpy>=1.0 in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->notebook<7->jupyterlab<4.0.0,>=3.4.5->PySUS) (1.6.3)
Requirement already satisfied: psutil in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from ipykernel->notebook<7->jupyterlab<4.0.0,>=3.4.5->PySUS) (5.9.2)
Requirement already satisfied: pure-eval in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (0.2.2)
Requirement already satisfied: asttokens in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (2.0.8)
Requirement already satisfied: executing in c:\users\otavi\appdata\local\programs\python\python310\lib\site-packages (from stack-data->ipython->jupyterlab<4.0.0,>=3.4.5->PySUS) (1.1.0)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for wget, since package 'wheel' is not installed.
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Building wheels for collected packages: pyreaddbc
  Building wheel for pyreaddbc (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyreaddbc (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      C:\Users\otavi\AppData\Local\Temp\pip-install-nrhacx2h\pyreaddbc_c92f5d62c1db437f9316ae4b2e0f28a7\pyreaddbc/_readdbc.so
      generating .\pyreaddbc\_readdbc.c
      (already up-to-date)
      the current directory is 'C:\\Users\\otavi\\AppData\\Local\\Temp\\pip-install-nrhacx2h\\pyreaddbc_c92f5d62c1db437f9316ae4b2e0f28a7'
      running build_ext
      building 'pyreaddbc._readdbc' extension
      Traceback (most recent call last):
        File "C:\Users\otavi\AppData\Local\Temp\pip-install-nrhacx2h\pyreaddbc_c92f5d62c1db437f9316ae4b2e0f28a7\pyreaddbc\_build_readdbc.py", line 37, in <module>
          ffibuilder.compile(
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\cffi\api.py", line 725, in compile
          return recompile(self, module_name, source, tmpdir=tmpdir,
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\cffi\recompiler.py", line 1564, in recompile
          outputfilename = ffiplatform.compile('.', ext,
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\cffi\ffiplatform.py", line 22, in compile
          outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\cffi\ffiplatform.py", line 51, in _build
          dist.run_command('build_ext')
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 344, in compile
          self.initialize()
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      Traceback (most recent call last):
        File "C:\Users\otavi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\otavi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\otavi\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 67, in build_wheel
          return WheelBuilder.make_in(poetry, Path(wheel_directory))
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 79, in make_in
          wb.build(target_dir=directory)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 109, in build
          self._build(zip_file)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 157, in _build
          self._run_build_script(self._package.build_script)
        File "C:\Users\otavi\AppData\Local\Temp\pip-build-env-8aw25hz7\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 217, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "C:\Users\otavi\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:/Users/otavi/AppData/Local/Programs/Python/Python310/python.exe', 'pyreaddbc/_build_readdbc.py']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyreaddbc
Failed to build pyreaddbc
ERROR: Could not build wheels for pyreaddbc, which is required to install pyproject.toml-based projects
PS C:\Users\otavi\GitHub\MEGA_SENA-GERADOR_NUMERO_AI> 
```

**Comment by fccoelho** [comment]
@otavioaugust1 you need to Microsoft visual studio to compile one of the dependencies of PySUS. From your error message:
```
Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by MarciaGodoy** [comment]
I installed the Microsoft visual, but the install failed.

**Comment by MarciaGodoy** [comment]
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/AlertaDengue/PySUS.git
  Cloning https://github.com/AlertaDengue/PySUS.git to /tmp/pip-req-build-3skfsjz7
  Running command git clone -q https://github.com/AlertaDengue/PySUS.git /tmp/pip-req-build-3skfsjz7
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting dbfread==2.0.7
  Using cached dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Collecting pytz==2022.2.1
  Downloading pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
     |████████████████████████████████| 500 kB 5.3 MB/s 
Collecting jupyterlab<4.0.0,>=3.4.5
  Using cached jupyterlab-3.4.8-py3-none-any.whl (8.8 MB)
ERROR: Could not find a version that satisfies the requirement pyreaddbc==1.0.0 (from pysus) (from versions: none)
ERROR: No matching distribution found for pyreaddbc==1.0.0

**Comment by MarciaGodoy** [comment]
[end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyreaddbc
Failed to build pyreaddbc
ERROR: Could not build wheels for pyreaddbc, which is required to install pyproject.toml-based projects

**Comment by fccoelho** [comment]
For now PySUS is having building issues on windows.

We are looking into that. But for Now I suggest using WSL (installing
Ubuntu from the windows store) or running PySUS on Google colab.

Em sáb., 8 de out. de 2022 02:14, Marcia Godoy ***@***.***>
escreveu:

**Comment by caibealves** [comment]
I got these same errors when trying to installing on linux, using python 3.9, but after I upgrade to 3.11 version the installation worked.
I also installed in another pc with python 3.8 version without problem.

**Comment by AlineGobbi** [comment]
![Captura de tela 2024-01-04 151442](https://github.com/AlertaDengue/PySUS/assets/95905428/144b2d10-141c-45bd-80f5-9fb24f0b3e7a)

Tive um problema parecido

**Comment by fccoelho** [comment]
> ![Captura de tela 2024-01-04 151442](https://private-user-images.githubusercontent.com/95905428/294264189-144b2d10-141c-45bd-80f5-9fb24f0b3e7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzgxNzcsIm5iZiI6MTcwNDczNzg3NywicGF0aCI6Ii85NTkwNTQyOC8yOTQyNjQxODktMTQ0YjJkMTAtMTQxYy00NWJkLTgwZjUtOWZiMjRmMGIzZTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE4MTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMDEwODNlZmIxMTkwYThlYzJlMzQzZDk4MDM5YjgzZGI4NzU2MTRiNTJhNzEzZjlmY2JlYWM0NDJhNTFmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SXYy8rV5P0VZWQgIzlpb1_zaBUftADCpY93MyfqgZMY)
> 
> Tive um problema parecido python esta na versão 3.11

Este é o erro que dá quando se tenta instalar no Windows. Ainda não é possível instalar o pyreaddbc no windows.

**Comment by luabida** [comment]
same issue as https://github.com/AlertaDengue/PySUS/issues/205
